import {
    faSchool,
    faBook,
    faBriefcase,
    faUtensils,
    faDumbbell,
    faCalendarCheck,
    faCalendarAlt,
    faCar,
    faStethoscope,
    faHeartbeat,
    faSpa,
    faShoppingCart,
    faPlane,
    faPhone,
    faGlassCheers,
    faCalendar as faRegCalendar,
  } from '@fortawesome/free-solid-svg-icons';
  
  export const keywordIconMap: Record<string, any> = {
    school: faSchool,
    study: faBook,
    work: faBriefcase,
    job: faBriefcase,
    cook: faUtensils,
    lunch: faUtensils,
    dinner: faUtensils,
    gym: faDumbbell,
    workout: faDumbbell,
    meeting: faCalendarCheck,
    event: faCalendarAlt,
    drive: faCar,
    driving: faCar,
    doctor: faStethoscope,
    health: faHeartbeat,
    relax: faSpa,
    shopping: faShoppingCart,
    travel: faPlane,
    call: faPhone,
    party: faGlassCheers,
    default: faRegCalendar,
  };